#!/usr/bin/env expect

set user [lindex $argv 0]
set ip [lindex $argv 1]


spawn ssh "$user\@$ip"

set timeout 6
expect "Password:" {
	send "this is what we need to figure out"
	expect "Password:" {
		send "its also taking a while, its way to slow to be practical"
		expect "Password:" {
			send "yep."
		}
	}
} "(yes/no)?" {
	send "yes"
} "Connection refused" {
	exit 1
}

interact